package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;

interface DefenceUnitInterface {

    public void isAreaChecked(String CheckedValue);
    public void PositionValueMethod(int positionValue);
    //public void Count(int temp);
    public void sendMsg(String tempMmsg,int tempIndex);
       
    

}

/**
 *
 * @author sandhanu
 */
public class MainController extends javax.swing.JFrame {
   
    private static MainController main;
    
    /**
     * Creates new form MainController
     */
    public MainController() {
        initComponents();
        setVisible(true);

    }
     public static MainController getInstant(){
        if(main==null){
           
            main=new MainController();
            
        }
        return main;
    }
    private final ArrayList<DefenceUnitInterface> defenceUnits = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Position = new javax.swing.JSlider();
        PositionValue = new javax.swing.JLabel();
        PositionText = new javax.swing.JLabel();
        Area_Clear_MainController = new javax.swing.JCheckBox();
        lblHelicopterSoldierCount = new javax.swing.JLabel();
        lblHeicopterAmmoCount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jTextField = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jComboBoxSelectDefenceUnits = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTankSoldierCount = new javax.swing.JLabel();
        lblTankAmmoCount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSubSoldierCount = new javax.swing.JLabel();
        lblSubAmmoCount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainController");
        setLocation(new java.awt.Point(800, 500));

        Position.setBackground(new java.awt.Color(255, 255, 255));
        Position.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Position.setForeground(new java.awt.Color(255, 51, 51));
        Position.setMajorTickSpacing(10);
        Position.setMinorTickSpacing(5);
        Position.setPaintLabels(true);
        Position.setPaintTicks(true);
        Position.setValue(0);
        Position.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PositionStateChanged(evt);
            }
        });

        PositionValue.setBackground(new java.awt.Color(255, 255, 255));
        PositionValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PositionValue.setForeground(new java.awt.Color(0, 0, 255));
        PositionValue.setText("0");

        PositionText.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        PositionText.setForeground(new java.awt.Color(153, 0, 0));
        PositionText.setText("Position");

        Area_Clear_MainController.setBackground(new java.awt.Color(255, 102, 51));
        Area_Clear_MainController.setText("Area Clear");
        Area_Clear_MainController.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Area_Clear_MainControllerActionPerformed(evt);
            }
        });

        lblHelicopterSoldierCount.setText("0");

        lblHeicopterAmmoCount.setText("0");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jComboBoxSelectDefenceUnits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AllDefenceUnits", "Helicopter", "Tank", "SubMarine" }));
        jComboBoxSelectDefenceUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectDefenceUnitsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Helicopter");

        jLabel2.setText("Soldier Count");

        jLabel3.setText("Ammo Count");

        lblTankSoldierCount.setText("0");

        lblTankAmmoCount.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tank");

        lblSubSoldierCount.setText("0");

        lblSubAmmoCount.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("SubMarine");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Area_Clear_MainController, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHelicopterSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTankSoldierCount)
                                            .addComponent(lblSubSoldierCount))
                                        .addGap(91, 91, 91)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSend)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxSelectDefenceUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblHeicopterAmmoCount)
                                    .addComponent(lblTankAmmoCount)
                                    .addComponent(lblSubAmmoCount)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PositionText)
                                        .addGap(18, 18, 18)
                                        .addComponent(PositionValue))
                                    .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PositionText)
                    .addComponent(PositionValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Area_Clear_MainController, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHelicopterSoldierCount)
                    .addComponent(lblHeicopterAmmoCount)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTankSoldierCount)
                            .addComponent(jLabel4)
                            .addComponent(lblTankAmmoCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubSoldierCount)
                            .addComponent(lblSubAmmoCount)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSend)
                            .addComponent(jComboBoxSelectDefenceUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PositionStateChanged
        PositionValue.setText(Position.getValue() + ""); 
            for (DefenceUnitInterface obj : defenceUnits) {
            obj.PositionValueMethod(Position.getValue());
        }   
        
        // TODO add your handling code here:
    }//GEN-LAST:event_PositionStateChanged

    private void Area_Clear_MainControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area_Clear_MainControllerActionPerformed
        for (DefenceUnitInterface obj : defenceUnits) {
            obj.isAreaChecked(Area_Clear_MainController.isSelected() == true ? "Area Cleared" : "Area Not Cleared");
        }
    }//GEN-LAST:event_Area_Clear_MainControllerActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jComboBoxSelectDefenceUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectDefenceUnitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSelectDefenceUnitsActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        int tempIndex=jComboBoxSelectDefenceUnits.getSelectedIndex();
        String tempMsg="MainController msgCnter :- "+jTextField.getText()+"\n";
        for (DefenceUnitInterface obj : defenceUnits) {
            obj.sendMsg(tempMsg,tempIndex);
        }
      
            jTextArea.setText( jTextArea.getText()+tempMsg);
        
        
    }//GEN-LAST:event_btnSendActionPerformed
    public void addcomponent(DefenceUnitInterface v1) {
        defenceUnits.add(v1);
    }
    public void setLblHelicopterSoldierCount(int HSCount){
    lblHelicopterSoldierCount.setText(HSCount+"");
    }
    public void setLblHelicopterAmmoCount(int HACount){
    lblHeicopterAmmoCount.setText(HACount+"");
    }
    public void setLblTankSoldierCount(int TSCount){
    lblTankSoldierCount.setText(TSCount+"");
    }
    public void setLblTankAmmoCount(int TACount){
    lblTankAmmoCount.setText(TACount+"");
    }
     public void setLblSubSoldierCount(int SSCount){
    lblSubSoldierCount.setText(SSCount+"");
    }
    public void setLblSubAmmoCount(int SACount){
    lblSubAmmoCount.setText(SACount+"");
    }
    public void AddTextArea(String tempreceived){
     
    jTextArea.setText( jTextArea.getText()+tempreceived);
    }

//    public String isAreaChecked() {
//        return Area_Clear_MainController.isSelected() == true ? "Area Cleared" : "Area Not Cleared";
//    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Area_Clear_MainController;
    private javax.swing.JSlider Position;
    private javax.swing.JLabel PositionText;
    private javax.swing.JLabel PositionValue;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<String> jComboBoxSelectDefenceUnits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField;
    private javax.swing.JLabel lblHeicopterAmmoCount;
    private javax.swing.JLabel lblHelicopterSoldierCount;
    private javax.swing.JLabel lblSubAmmoCount;
    private javax.swing.JLabel lblSubSoldierCount;
    private javax.swing.JLabel lblTankAmmoCount;
    private javax.swing.JLabel lblTankSoldierCount;
    // End of variables declaration//GEN-END:variables

}
